import keyMirror from 'react/lib/keyMirror';

export default keyMirror({
  CREATE_CONFIG: null,
  CREATE_ADD_SCRIPT: null,
  CREATE_UPDATE_DOMAIN: null,
  CREATE_REMOVE_SCRIPT: null,
  CREATE_UPDATE_SCRIPT: null,
  CREATE_UPDATE_REDIRECT: null,
  CREATE_UPDATE_REWRITE: null,
  UPDATE_CONFIG: null,
  UPDATE_ADD_SCRIPT: null,
  UPDATE_UPDATE_DOMAIN: null,
  UPDATE_REMOVE_SCRIPT: null,
  UPDATE_UPDATE_SCRIPT: null,
  UPDATE_UPDATE_REDIRECT: null,
  UPDATE_UPDATE_REWRITE: null,
  UPDATE_SET_CONFIGS: null,
  UPDATE_GET_SELECTED: null
});
